/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;
import Controller.Controller;
import Controller.InfoObject;
import classes.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.PrintWriter;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
/**
 *
 * @author Santiago
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    private int cIndex;
    private int lIndex;
    private String CLname;
    private String solution;
    private String content;
    private String message;
    Controller controller;
            
    public Frame() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH); 
        controller = new Controller();
        initComponents();
        changeLessonInformation(0,0);
    }

    
    private void changeLessonInformation(int cIndex, int lIndex){
        InfoObject info = controller.getLessonInfo(cIndex, lIndex);
        CLname = info.clName;
        this.cIndex = info.cIndex;
        this.lIndex = info.lIndex;
        content = info.content;
        solution = info.solution;
        message = info.message;
        
        contentLabel.setText(content);
        headerLabel.setText(CLname);
        messageLabel.setText(message);
        controller.updateButtons(cIndex,lIndex);
        answerPane.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerPane = new javax.swing.JEditorPane();
        runButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageLabel = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        contentLabel = new javax.swing.JLabel();
        canvas = new classes.Canvas();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        l11 = new javax.swing.JMenuItem();
        l12 = new javax.swing.JMenuItem();
        l13 = new javax.swing.JMenuItem();
        l14 = new javax.swing.JMenuItem();
        l15 = new javax.swing.JMenuItem();
        l16 = new javax.swing.JMenuItem();
        l17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        l21 = new javax.swing.JMenuItem();
        l22 = new javax.swing.JMenuItem();
        l23 = new javax.swing.JMenuItem();
        l24 = new javax.swing.JMenuItem();
        l25 = new javax.swing.JMenuItem();
        l26 = new javax.swing.JMenuItem();
        l27 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        l31 = new javax.swing.JMenuItem();
        l32 = new javax.swing.JMenuItem();
        l33 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        answerPane.setToolTipText("Escribe el código aqui");
        answerPane.setName("Escribe tus comandos aquí"); // NOI18N
        jScrollPane1.setViewportView(answerPane);

        runButton.setText("Ejecutar!");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        messageLabel.setEditable(false);
        messageLabel.setColumns(20);
        messageLabel.setRows(5);
        jScrollPane2.setViewportView(messageLabel);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        headerLabel.setText("jLabel1");
        headerLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        next.setText("Siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setText("Anterior");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        contentLabel.setText("Content ");
        contentLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contentLabel.setAutoscrolls(true);
        contentLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next)
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(back))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu4.setText("   Capítulo 1  ");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        l11.setText("Lección 1.1");
        l11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l11ActionPerformed(evt);
            }
        });
        jMenu4.add(l11);

        l12.setText("Lección 1.2");
        l12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l12ActionPerformed(evt);
            }
        });
        jMenu4.add(l12);

        l13.setText("Lección 1.3");
        l13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l13ActionPerformed(evt);
            }
        });
        jMenu4.add(l13);

        l14.setText("Lección 1.4");
        l14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l14ActionPerformed(evt);
            }
        });
        jMenu4.add(l14);

        l15.setText("Lección 1.5");
        l15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l15ActionPerformed(evt);
            }
        });
        jMenu4.add(l15);

        l16.setText("Lección 1.6");
        l16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l16ActionPerformed(evt);
            }
        });
        jMenu4.add(l16);

        l17.setText("Lección 1.7");
        l17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l17ActionPerformed(evt);
            }
        });
        jMenu4.add(l17);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("   Capítulo 2   ");

        l21.setText("Lección 2.1");
        l21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l21ActionPerformed(evt);
            }
        });
        jMenu5.add(l21);

        l22.setText("Lección 2.2");
        l22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l22ActionPerformed(evt);
            }
        });
        jMenu5.add(l22);

        l23.setText("Lección 2.3");
        l23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l23ActionPerformed(evt);
            }
        });
        jMenu5.add(l23);

        l24.setText("Lección 2.4");
        l24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l24ActionPerformed(evt);
            }
        });
        jMenu5.add(l24);

        l25.setText("Lección 2.5");
        l25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l25ActionPerformed(evt);
            }
        });
        jMenu5.add(l25);

        l26.setText("Lección 2.6");
        l26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l26ActionPerformed(evt);
            }
        });
        jMenu5.add(l26);

        l27.setText("Lección 2.7");
        l27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l27ActionPerformed(evt);
            }
        });
        jMenu5.add(l27);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("   Capítulo 3   ");

        l31.setText("Lección 3.1");
        l31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l31ActionPerformed(evt);
            }
        });
        jMenu6.add(l31);

        l32.setText("Lección 3.2");
        l32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l32ActionPerformed(evt);
            }
        });
        jMenu6.add(l32);

        l33.setText("Lección 3.3");
        l33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l33ActionPerformed(evt);
            }
        });
        jMenu6.add(l33);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("   Capítulo 4   ");
        jMenuBar2.add(jMenu7);

        jMenu9.setText("Práctica Libre");
        jMenuBar2.add(jMenu9);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton))
                    .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l11ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(0,0);
    }//GEN-LAST:event_l11ActionPerformed

    private void l31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l31ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(2,0);
    }//GEN-LAST:event_l31ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void l12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l12ActionPerformed
        // TODO add your handling code here:

        changeLessonInformation(0,1);

    }//GEN-LAST:event_l12ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        int[] nextLesson = controller.getNextLesson(cIndex, lIndex);
        cIndex = nextLesson[0];
        lIndex = nextLesson[1];
        changeLessonInformation(cIndex, lIndex);
    }//GEN-LAST:event_nextActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        String answer = answerPane.getText();
        controller.runInterpreter(answer);
        message = messageLabel.getText();
        message = message + controller.checkSolution(cIndex, lIndex, answer);
        messageLabel.setText(message);
        
    }//GEN-LAST:event_runButtonActionPerformed

    private void l21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l21ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,0);
    }//GEN-LAST:event_l21ActionPerformed

    private void l32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l32ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(2,1);
    }//GEN-LAST:event_l32ActionPerformed

    private void l33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l33ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(2,2);
    }//GEN-LAST:event_l33ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        int[] previousLesson = controller.getPrevoiusLesson(cIndex, lIndex);
        cIndex = previousLesson[0];
        lIndex = previousLesson[1];
        changeLessonInformation(cIndex, lIndex);
    }//GEN-LAST:event_backActionPerformed

    private void l15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l15ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(0,4);
    }//GEN-LAST:event_l15ActionPerformed

    private void l13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l13ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(0,2);
    }//GEN-LAST:event_l13ActionPerformed

    private void l14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l14ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(0,3);
    }//GEN-LAST:event_l14ActionPerformed

    private void l16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l16ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(0,5);
    }//GEN-LAST:event_l16ActionPerformed

    private void l17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l17ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(0, 6);
    }//GEN-LAST:event_l17ActionPerformed

    private void l22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l22ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,1);
    }//GEN-LAST:event_l22ActionPerformed

    private void l26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l26ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,5);
    }//GEN-LAST:event_l26ActionPerformed

    private void l23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l23ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,2);
    }//GEN-LAST:event_l23ActionPerformed

    private void l24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l24ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,3);
    }//GEN-LAST:event_l24ActionPerformed

    private void l25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l25ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,4);
    }//GEN-LAST:event_l25ActionPerformed

    private void l27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l27ActionPerformed
        // TODO add your handling code here:
        changeLessonInformation(1,6);
    }//GEN-LAST:event_l27ActionPerformed
    public void error(String s){
        this.messageLabel.setText(s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Frame f=new Frame();
                 f.setVisible(true);
                 f.setResizable(false);
                 
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane answerPane;
    public static javax.swing.JButton back;
    public classes.Canvas canvas;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JMenuItem l11;
    public static javax.swing.JMenuItem l12;
    public static javax.swing.JMenuItem l13;
    public static javax.swing.JMenuItem l14;
    public static javax.swing.JMenuItem l15;
    public static javax.swing.JMenuItem l16;
    public static javax.swing.JMenuItem l17;
    public static javax.swing.JMenuItem l21;
    public static javax.swing.JMenuItem l22;
    public static javax.swing.JMenuItem l23;
    public static javax.swing.JMenuItem l24;
    public static javax.swing.JMenuItem l25;
    public static javax.swing.JMenuItem l26;
    public static javax.swing.JMenuItem l27;
    public static javax.swing.JMenuItem l31;
    public static javax.swing.JMenuItem l32;
    public static javax.swing.JMenuItem l33;
    private javax.swing.JTextArea messageLabel;
    public static javax.swing.JButton next;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
